# fly.toml app configuration file generated for skyroute on 2025-10-08T14:29:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'skyroute'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  MAIL_HOST = '${MAIL_HOST}'
  MAIL_PASSWORD = '${MAIL_PASSWORD}'
  MAIL_PORT = '${MAIL_PORT}'
  MAIL_PROPERTIES_MAIL_SMTP_AUTH = '${MAIL_PROPERTIES_MAIL_SMTP_AUTH}'
  MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE = '${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}'
  MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED = '${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED}'
  MAIL_USERNAME = '${MAIL_USERNAME}'
  MYSQL_PASSWORD = '${MYSQL_PASSWORD}'
  MYSQL_URL = '${MYSQL_URL}'
  MYSQL_USER = '${MYSQL_USER}'
  SERVER_ADDRESS = '0.0.0.0'
  SERVER_PORT = '8080'
  SPRING_DATASOURCE_PASSWORD = '${SPRING_DATASOURCE_PASSWORD}'
  SPRING_DATASOURCE_URL = '${SPRING_DATASOURCE_URL}'
  SPRING_DATASOURCE_USERNAME = '${SPRING_DATASOURCE_USERNAME}'
  SPRING_PROFILES_ACTIVE = 'fly'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/actuator/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
