# fly.toml app configuration file
app = 'skyroute'
primary_region = 'cdg'

[build]

[env]
SPRING_PROFILES_ACTIVE = "fly"
SERVER_ADDRESS = "0.0.0.0"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

# Health check configuration
[http_service.checks]
[http_service.checks.alive]
type = "http"
interval = "15s"
timeout = "10s"
grace_period = "30s"
method = "GET"
path = "/actuator/health"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024