# H2 datasource configuration:
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    url: jdbc:h2:mem:testdb
    user: sa
    password: password
  h2:
    console:
      enabled: true

