spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/V1__Create_users_table.sql,classpath:db/migration/V2__Create_airports_table.sql,classpath:db/migration/V3__Create_aircrafts_table.sql,classpath:db/migration/V4__Create_routes_table.sql,classpath:db/migration/V5__Create_flights_table.sql,classpath:db/migration/V6__Create_booking_table.sql,classpath:db/migration/V8__Add_password_reset_fields.sql
      data-locations: classpath:db/migration/V7__Insert_test_data.sql,classpath:db/migration/V9__Expand_test_data.sql
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
            required: ${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED}
