# Job to fix failed Flyway migration V10
# Run this once manually to clean up failed migration record
# After successful execution, delete this file from kustomization.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-repair-v10
  labels:
    app: skyroute
    component: database-maintenance
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: skyroute
        component: database-maintenance
    spec:
      restartPolicy: Never
      containers:
        - name: mysql-repair
          image: mysql:8.0
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_DATABASE
              value: "skyroute"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
          command:
            - /bin/bash
            - -c
            - |
              echo "=== Flyway V10 Migration Repair ==="
              echo "Connecting to MySQL at ${MYSQL_HOST}..."

              mysql -h ${MYSQL_HOST} -u ${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} <<EOF

              -- Show current failed migration
              SELECT 'Before cleanup:' as status;
              SELECT version, description, installed_on, success 
              FROM flyway_schema_history 
              WHERE version = '10';

              -- Delete failed migration record
              DELETE FROM flyway_schema_history 
              WHERE version = '10' AND success = 0;

              -- Also delete success=1 if exists (to allow re-run)
              DELETE FROM flyway_schema_history 
              WHERE version = '10' AND success = 1;

              -- Confirm deletion
              SELECT 'After cleanup:' as status;
              SELECT version, description, installed_on, success 
              FROM flyway_schema_history 
              WHERE version = '10';

              EOF

              if [ $? -eq 0 ]; then
                echo "SUCCESS: V10 migration record removed"
                echo "Next: Application will re-run V10 with fixed SQL"
              else
                echo "ERROR: Failed to clean up migration"
                exit 1
              fi
